org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true

mod.version=1.2.1
mod.group=com.sxilverr.lootall
mod.id=lootall
mod.name=Loot All

mod.mc_dep_fabric=[VERSIONED]
mod.mc_dep_forgelike=[VERSIONED]

deps.fabric_loader=0.16.5
deps.fabric_api=[VERSIONED]
deps.forge_loader=[VERSIONED]
deps.neoforge_loader=[VERSIONED]
